### model
model_name_or_path: /mnt/isilon/llm_collaborative_deidentified/Llama3/Llama-3.1-8B-Instruct
trust_remote_code: true
quantization_bit: 4

### method
stage: sft
do_train: true
finetuning_type: lora
lora_dropout: 0.1
lora_rank: 8
lora_alpha: 32
lora_target: q_proj,v_proj,o_proj  # or "all" if memory allows

### dataset
#dataset_dir: llama31_8b_outputs/fold_4             # <- adjust per fold
dataset_dir: outputs_train_full             # <- adjust per fold
dataset: train
#eval_dataset: val
template: llama3
cutoff_len: 5000 
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: outputs_train_full/model_llama31_8b
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_total_limit: 1
save_only_model: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000


